![np logo](./data/np_logo.png)

## What is Numpy?

NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python

## Why Use NumPy?

In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called `ndarray`, it provides a lot of supporting functions that make working with `ndarray` very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

<a id="section-one"></a>
# Section  1 - Import Numpy & basic check

In [ ]:
import numpy as np

In [ ]:
# code to check version of numpy library

np.__version__

In [ ]:
#  to display all the contents of the numpy namespace, you can type this, np.<TAB>
# And to display NumPy’s built-in documentation, you can use this: np?

np?

In [ ]:
p=np.array([3.14,6,8,9,10,15,19,21])
print(p)

## Array creation

NumPy arrays can be created from Python lists

In [ ]:
my_array = np.array([1, 2, 3])
my_array

NumPy supports array of arbitrary dimension. For example, we can create two-dimensional arrays (e.g. to store a matrix) as follows

In [ ]:
my_2d_array = np.array([[1, 2, 3], [4, 5, 6]])
my_2d_array

The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

In [ ]:
print(my_2d_array.shape)

Numpy also provides many functions to create arrays:

In [ ]:
a = np.zeros((2,2))  # Create an array of all zeros
print(a)

In [ ]:
b = np.ones((1,2))   # Create an array of all ones
print(b)

In [ ]:
c = np.full((2,2), 7) # Create a constant array
print(c)

In [ ]:
d = np.eye(2)        # Create a 2x2 identity matrix
print(d)

In [ ]:
e = np.random.random((2,2)) # Create an array filled with random values
print(e)

In [ ]:
# Create a numpy with random integers and size
a = np.random.randint(10, size = 5)

print(a)

In [ ]:
# Create a numpy with random integers and size
a=np.random.randint(1,20,size=(2,3))

print(a,'a.shape :',a.shape)
print('a.dtype :',a.dtype)

In [ ]:
np.arange([1, 2, 3.4, 6.4, 9])

## NumPy Array properties
![np attributes](data/np_desc.png)

## Datatypes

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [ ]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # Force a particular datatype

print(x.dtype, y.dtype, z.dtype)

*Note:* you can check [Numpy documentation](https://numpy.org/doc/stable/user/basics.types.html) website to see the full list of supported datatype.

## Array indexing and slicing

Numpy offers several ways to index into arrays.

Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [ ]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

A slice of an array is a view into the same data, so modifying it will modify the original array.

In [ ]:
print(a[0, 1])
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1]) 

You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array. Note that this is quite different from the way that MATLAB handles array slicing:

## Basic operations

In NumPy, we express computations directly over arrays. This makes the code much more succint

Arithmetic operations can be performed directly over arrays. For instance, assuming two arrays have a compatible shape, we can add them as follows

In [ ]:
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])
array_a + array_b

Compare this with the equivalent computation using a for loop

In [ ]:
array_out = np.zeros_like(array_a)
for i in range(len(array_a)):
    array_out[i] = array_a[i] + array_b[i]
array_out

Not only this code is more verbose, it will also run much more slowly.

In NumPy, functions that operates on arrays in an element-wise fashion are called [universal functions](https://numpy.org/doc/stable/reference/ufuncs.html). For instance, this is the case of `np.sin`

In [ ]:
np.sin(array_a)

Vector inner product can be performed using `np.dot`

In [ ]:
np.dot(array_a, array_b)

In [ ]:
array_a * array_b

When the two arguments to `np.dot` are both 2d arrays, `np.dot` becomes matrix multiplication

In [ ]:
array_A = np.random.rand(5, 3)
array_B = np.random.randn(3, 4)
np.dot(array_A, array_B)

Matrix transpose can be done using `.transpose()` or `.T` for short

In [ ]:
array_A.T

### conditions and masking


In [ ]:
rd_arr = np.random.randint(2,200, size=30)
rd_arr

In [ ]:
rd_arr < 74

In [ ]:
f = rd_arr[rd_arr < 74]
f

## Computation on Arrays: Broadcasting

In [ ]:
a = np.array([1, 1, 2])
b = np.array([5, 6, 5])
a + b

![np brodcasting](data/np_brodcast.png)

In [ ]:
# Rules of Broadcasting
# Broadcasting in NumPy follows a strict set of rules to determine the interaction between the two arrays
# Rule 1: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.
# Rule 2: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape
# Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

#Broadcasting example 1
#Let’s look at adding a two-dimensional array to a one-dimensional array:

M=np.ones((2,3))
a=np.arange((3))

# Let’s consider an operation on these two arrays. The shapes of the arrays are:

M.shape

In [ ]:
a.shape
# We see by rule 1 that the array a has fewer dimensions, so we pad it on the left with ones:

In [ ]:
M+a   # addition will be a 2x3 matrix

In [ ]:
# Broadcasting example 2

# Let’s take a look at an example where both arrays need to be broadcast:

a=np.arange(3).reshape((3,1))
b=np.arange(3)

a+b

In [ ]:
a+5

In [ ]:
# We can similarly extend this to arrays of higher dimension. Observe the result when we add a one-dimensional array to a two-dimensional array

M=np.ones((3,3))
M

In [ ]:
M+a
# Here the one-dimensional array a is stretched, or broadcast, across the second dimension in order to match the shape of M

In [ ]:
a

## Numpy Routines


In [ ]:
# Fast Sorting in NumPy: np.sort and np.argsort

x = np.array([2, 1, 4, 3, 5])
np.sort(x)

In [ ]:
x.sort()
print(x)

In [ ]:
np.sin(x)

In [ ]:
np.sum(x)

In [ ]:
x.min()

More about Numpy functions can be found on [Numpy-documentation-routines](https://numpy.org/doc/stable/reference/ufuncs.html)